### ISSUE TITLE
NodeModulesFinder interfers with collectstatic

### ISSUE THREAD

**Issue by andhdo** [whitespy/django-node-assets#1]
adding this module inside STATICFILES_FINDERS makes that collectstatic procedure of django copies also all sources to STATIC_ROOT dir.

**Comment by whitespy** [comment]
Could you describe in more detail your case? Thanks.

**Comment by andhdo** [comment]
Of course, @whitespy;

I've created a brand new application with django admin; 
then, i've added settings configuration for this module: 

`STATIC_ROOT`  = os.path.join(PROJECT_ROOT, '__collectstatic')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'node_modules'),
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_FINDERS = [
    # default
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # added
    **#** 'django_node_assets.finders.NodeModulesFinder',
]`

after that; i've added the normal configuration of node_modules using yarn: 

```
yarn init --yes
yarn add bootstrap-3@npm:bootstrap@3.4.1
yarn add bootstrap-4@npm:bootstrap
```
(i dit it by this way because i'm using two bootstrap versions)

Then, i've executed the collect static command: 
`python manage.py collectstatic --noinput`

With NodeModulesFinder commented, collect command to send static resources to __collectstatic is executed without any problem: it copies only static resources (inside static directory by default of every registered application in settings.INSTALLED_APPS ).


But when i add the filter (NodeModulesFinder), it copies all sources of the base directory of the applicationto the __collectstatic module.  

As a workaround, i've only added node_modules to static files definitions: 

`STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'node_modules'),
    os.path.join(BASE_DIR, 'static'),
]`

and stopped using django-node-assets configuration in the solution, and then use the modules of node without the node_modules prefix: 

`<link rel="stylesheet" href='{% static "bootstrap-3/dist/css/bootstrap.min.css" %}'>` or `<link rel="stylesheet" href='{% static "bootstrap-4/dist/css/bootstrap.min.css" %}'>`

**Comment by whitespy** [comment]
Thanks. I have understood. Try remove os.path.join(BASE_DIR, 'node_modules') from STATICFILES_DIRS and set NODE_MODULES_ROOT to os.path.join(BASE_DIR, 'node_modules').
