### ISSUE TITLE
Windows: OSError: symbolic link privaledge not held

### ISSUE THREAD

**Issue by idahogray** [whitespy/django-node-assets#2]
I am trying to run this on Windows 10 and receiving the following error: `OSError: symbolic link privilege not held`. Is there a way to accomplish the same thing without using symlinks for Windows users?

The error is caused by line 16 of npminstall.py.

**Comment by whitespy** [comment]
Hi. I guess this error occurred because Windows doesn't support  symbolic link. I will fix this error soon. Thanks for issue.

**Comment by whitespy** [comment]
Fixed on release **0.9.5**
