### ISSUE TITLE
When running `npminstall` arguments are ignored

### ISSUE THREAD

**Issue by pdechery** [whitespy/django-node-assets#4]
I was trying to run the `npminstall` command to install my packages. Everytime I did the response was always the basic npm output when you just type "npm" and press enter. Nothing was installed.

```
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
npm help <term>    search for help on <term>
npm help npm       more involved overview
``` 

I was intrigued by that so I checked the code from the command (the `npminstall.py` file) and did a little research at the documentation of the `subprocess` package, used to issue the `npm install` command.

I finally got the script working by removing the `executable` argument and moving its information to `args`, like so:

```
with Popen(
                    args=[
                        '{} install'.format(getattr(settings, 'NODE_PACKAGE_MANAGER_EXECUTABLE', '/usr/bin/npm')),
                        '--no-package-lock',
                        '--prefix={}'.format(node_package_context.package_dir)
                    ],
                    #executable=getattr(settings, 'NODE_PACKAGE_MANAGER_EXECUTABLE', '/usr/bin/npm'),
                    shell=True,
                    stdout=PIPE,
                    stderr=STDOUT,
                    encoding='utf-8',
            ) as p:
```

I'm using Python 3.8 and Django 2.1.5 on Ubuntu 20.04. I run my Django app through a virtual environment.

Is there any hope for a new version fixing this? 

Thank you.

**Comment by TobsA13** [comment]
Yes, can also recreate this issue.

**Comment by whitespy** [comment]
Hello Pierre! Your approach will break package behavior. Please check out new package 0.9.11 release and try again. I have updated some npminstall management command features. If new package version will not help you, please check your project configuration. Looks like the **NODE_MODULES_ROOT** setting was not configured properly from your side.
