### ISSUE TITLE
Suggestion to drop NODE_PACKAGE_MANAGER_EXECUTABLE in favor of using npm cmd

### ISSUE THREAD

**Issue by Andrioden** [whitespy/django-node-assets#7]
Hi! Having to manage your executable directory across environments is going to be a bit painful. 

I have to configure locally

`NODE_PACKAGE_MANAGER_EXECUTABLE = "C:\\Users\\andre\\AppData\\Roaming\\npm\\npm.cmd"`

and a different config is needed for CI.

My suggestion is instead to natively use the `npm ` command directly, and therefor require every environment to have npm installed globally. You can then remove the config all together.

**Comment by whitespy** [comment]
Please check out the 0.9.13 release.

**Comment by whitespy** [comment]
Please check out the 0.9.13 release.
